$rg = "WWSOLabsBicepRG"
$loc = 'eastus'

az group create --resource-group $rg --location $loc
az group deployment create --resource-group $rg --template-file \script.bicep --mode Complete
#az group deployment create --resource-group $rg --template-file \script.bicep --mode Incremental -verbose
az group delete --resource-group $rg --yes

#Examples from AI knowledge base:
az group create --location westus --resource-group MyResourceGroup
#Create a new resource group in the West US region.

az group create --location westeurope --resource-group MyResourceGroup --tags {tags}
#Create a new resource group. (autogenerated)

az group list --query "[?location=='westus']"
#List all resource groups located in the West US region.#